jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==2.3.2 pytest==7.4.0 requests==2.31.0

      - name: Run tests
        run: pytest -q
